### ISSUE TITLE
Discourse API Endpoint has changed

### ISSUE THREAD

**Issue by herpaderpaldent** [herpaderpaldent/seat-discourse#11]
https://github.com/herpaderpaldent/seat-discourse/blob/6beb57505426359b89b2d479b1aad2160e70395e/src/Action/Discourse/Groups/Get.php#L20

Apparently the former endpoint has depreciated and moved to:

`{{base_url}}/groups.json?api_key={{api_key}}&api_username={{api_username}`

Need to adapt this URL and refactor to throw Exceptiones.

**Comment by ghost** [comment]
Would this be causing the error that my users cannot log into discourse now? keep getting
`127.0.0.1 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED`

**Comment by insuusvenerati** [comment]
@0wnedadmin  Anymore information than that one line? Logs from seAT and logs from discourse with verbose sso logging? I've been dealing with this issue for about 16 hours so I have a little experience with the symptoms.

**Comment by ghost** [comment]
attached are my logs.

im assuming this was an automatic upgrade and has caused havoc with everyone?
[discourse logs.zip](https://github.com/herpaderpaldent/seat-discourse/files/2475654/discourse.logs.zip)

**Comment by insuusvenerati** [comment]
There are no seAT or discourse logs. Nginx logs won't really tell us much.

**Comment by herpaderpaldent** [comment]
There are log entries from the sync job. That fails regarding the map method

**Comment by ghost** [comment]
[log.zip](https://github.com/herpaderpaldent/seat-discourse/files/2475668/log.zip)

i am not finding anything in seat logs relating to discourse, the attached is the whole content of /var/discourse/standalone/share/log

**Comment by insuusvenerati** [comment]
```
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED) subscribe failed, reconnecting in 1 second. Call stack ["/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:344:in `rescue in establish_connection'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:328:in `establish_connection'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:99:in `block in connect'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:98:in `connect'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:363:in `ensure_connected'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:118:in `call'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis.rb:889:in `block in get'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'", "/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis.rb:888:in `get'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/message_bus-2.1.5/lib/message_bus/backends/redis.rb:285:in `process_global_backlog'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/message_bus-2.1.5/lib/message_bus/backends/redis.rb:321:in `block in global_subscribe'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/message_bus-2.1.5/lib/message_bus/backends/redis.rb:334:in `global_subscribe'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/message_bus-2.1.5/lib/message_bus.rb:530:in `global_subscribe_thread'", "/var/www/discourse/vendor/bundle/ruby/2.5.0/gems/message_bus-2.1.5/lib/message_bus.rb:478:in `block in new_subscriber_thread'"]
```
`Job exception: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)`

Lot's of errors. Not sure if they are related.

**Comment by ghost** [comment]
its a completley fresh install 24 hours ago, followed the docs to the letter. could log in yesterday, and today i could not reach it.

when i click, discourse in seat, it sends me here https://127.0.0.1:7890/session/sso

**Comment by herpaderpaldent** [comment]
Laravel.log boys .... Search for the string discourse

The address @0wnedadmin looks odd though your env does probably have another address for discourse then your local machine

**Comment by ghost** [comment]
yes, its discourse.0wned.services the proxypass int he nginx is 127.0.0.1:7890

**Comment by insuusvenerati** [comment]
I would go over your setup again. I can't imagine why you would be redirected to localhost if everything is properly configured. Your env, callback urls, discourse sso urls etc should not contain localhost or 127.0.0.1 at all. 

> when i click, discourse in seat, it sends me here https://127.0.0.1:7890/session/sso

This for example means you have the DISCOURSE_URL variable set to https://127.0.0.1:7890/session/sso which is incorrect. It should be the URL to the discourse website. 

@0wnedadmin Let's take this to slack. This issue is not related to yours. https://eveseat.github.io/docs/about/contact/

**Comment by herpaderpaldent** [comment]
Changing label, since this is no longer a bug. OT had invalid SSL certs this lead to guzzle failing.

However this endpoint could be updated nevertheless in the near future
